import { hover } from './hover';
import { modal } from './modal';
import { header } from './header';
import { scroll } from './scroll';
import { backtop } from './backtop';
import { accordion } from './accordion';
import { remove } from './remove';
import { slider } from './slider';
import { tab } from './tab';
import { barGraph } from './barGraph';
import { cartWrapping } from './pages/cart-wrapping';
import { download } from './pages/download';
import { postcode } from './pages/postcode';
import { account } from './pages/account';
import { inquiry } from './pages/inquiry';
import { shippinginfoRegisterDialog } from './pages/shippinginfo-register-dialog';
import { family } from './pages/family';
import { cartDeliveryDate } from './pages/cart-delivery-date';
import { cartDeliveryAddress } from './pages/cart-delivery-address';
import { cartPayment } from './pages/cart-payment';
import { print } from './print';
import { fcMenu } from './pages/fcMenu';
import { calendar } from './calendar';
import { cart } from './pages/cart';
import { favorite } from './favorite';
import { cartAddPoint } from './pages/cart-add-point';
import { checksheet } from './pages/checksheet';

$( function () {
	hover();
	modal();
	header();
	scroll();
	backtop();
	accordion();
	remove();
    slider();
	tab();
	barGraph();
	print();
	calendar();
    favorite();

    // pages/*.js
    cartWrapping();
    download();
    postcode();
    account();
    inquiry();
    shippinginfoRegisterDialog();
    family();
    cartDeliveryDate();
    cartDeliveryAddress();
    cartPayment();
    fcMenu();
    cart();
    cartAddPoint();
    checksheet();
} );
